fix: input field parameters
ory/elements pull request #99
Opened 2023-03-03 14:32 UTC by misamu

Added pattern attribute to InputField.
Pattern to define allowed characters for the field

## Related Issue or Design Document

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation within the code base (if appropriate).

## Further comments

Related to [Kratos pull request 3143](https://github.com/ory/kratos/pull/3143)
- Adds `Pattern="[0-9]+"` to show error border on code field when non numeric character given
- Show error border in InputField when code field has focus and `:invalid `

2023-06-26 10:39 UTC, Benehiko commented
I would like to get this merged, but the PR in Kratos has not been merged yet. https://github.com/ory/kratos/pull/3143

2023-10-09 10:42 UTC, hperl approved these changes
LGTM.

@Benehiko, https://github.com/ory/kratos/pull/3143 -> https://github.com/ory/kratos/pull/3561 is now merged

2023-10-09 11:34 UTC, Benehiko requested changes

2023-10-09 11:34 UTC, Benehiko commented on src/react-components/ory/helpers/node.tsx
> +            fullWidth
I don't believe `fullWidth` exists anymore on the inputfield.

2023-10-09 11:34 UTC, Benehiko commented on src/react-components/ory/helpers/node.tsx
> +            fullWidth
https://github.com/ory/elements/blob/main/src/react-components/input-field.tsx#L14-L22C2

2023-10-13 11:36 UTC, Benehiko approved these changes

2023-10-13 11:44 UTC, merged